FROM duckietown/dt-gui-tools:daffy-amd64

RUN curl -fL http://docs.luxonis.com/_static/install_dependencies.sh | bash
RUN echo 'SUBSYSTEM=="usb", ATTRS{idVendor}=="03e7", MODE="0666"' | tee /etc/udev/rules.d/80-movidius.rules

RUN apt-get update && apt-get install -y \
    curl \
    udev \
    ffmpeg \
    libsm6 \
    libxext6 \
    libgl1-mesa-glx \
    libavcodec-dev \
    libavformat-dev \
    libswscale-dev \
    libtbb-dev \
    libjpeg-dev \
    libpng-dev \
    libtiff-dev \
    libdc1394-22-dev \
    usbutils \
    wget

RUN wget https://github.com/libusb/libusb/releases/download/v1.0.24/libusb-1.0.24.tar.bz2
RUN tar xf libusb-1.0.24.tar.bz2
RUN cd libusb-1.0.24 && \
    ./configure --disable-udev && \
    make -j && make install

RUN pip3 install -U \
    aido-protocols-daffy \
    depthai==2.4.0.0 \
    blobconverter==0.0.10

COPY assets/vnc/image/root/Desktop/. /root/Desktop/
COPY assets/vnc/image/root/Documents/. /root/Documents/

COPY assets/vnc/image/root/icons/. /root/.icons/
COPY assets/vnc/image/usr/bin/. /usr/bin/
COPY assets/vnc/image/opt/ros/noetic/share/rviz/. /opt/ros/noetic/share/rviz/


CMD ["dt-launcher-jupyter"]
