FROM duckietown/dt-gui-tools:daffy-amd64


RUN apt-get update && apt-get -y install libgtk-3-dev \
    software-properties-common \
    curl \
    apache2-utils \
    supervisor \
    nginx \
    sudo \
    net-tools \
    zenity \
    xz-utils \
    dbus-x11 \
    x11-utils \
    alsa-utils \
    mesa-utils \
    libgl1-mesa-dri \
    xvfb \
    x11vnc \
    vim-tiny \
    ttf-ubuntu-font-family \
    ttf-wqy-zenhei \
    lxde \
    gtk2-engines-murrine \
    gnome-themes-standard \
    gtk2-engines-pixbuf \
    gtk2-engines-murrine \
    arc-theme \
    curl \
    udev \
    ffmpeg \
    libsm6 \
    libxext6 \
    libgl1-mesa-glx \
    libavcodec-dev \
    libavformat-dev \
    libswscale-dev \
    libtbb-dev \
    libjpeg-dev \
    libpng-dev \
    libtiff-dev \
    libdc1394-22-dev \
    usbutils

RUN curl -fL http://docs.luxonis.com/_static/install_dependencies.sh | bash
RUN echo 'SUBSYSTEM=="usb", ATTRS{idVendor}=="03e7", MODE="0666"' | tee /etc/udev/rules.d/80-movidius.rules
RUN pip3 install depthai==2.7.1

CMD ["dt-launcher-jupyter"]
