FROM duckietown/dt-gui-tools:daffy-amd64

RUN apt-get update && apt-get install -y \
    bc \
    bzip2 \
    can-utils \
    freeglut3-dev \
    gstreamer1.0-alsa \
    gstreamer1.0-libav \
    gstreamer1.0-plugins-bad \
    gstreamer1.0-plugins-base \
    gstreamer1.0-plugins-good \
    gstreamer1.0-plugins-ugly \
    gstreamer1.0-tools \
    libgstreamer1.0-dev \
    libgstreamer-plugins-base1.0-dev \
    curl \
    udev \
    ffmpeg \
    libsm6 \
    libxext6 \
    libgl1-mesa-glx \
    libavcodec-dev \
    libavformat-dev \
    libswscale-dev \
    libtbb-dev \
    libjpeg-dev \
    libpng-dev \
    libtiff-dev \
    libdc1394-22-dev \
    usbutils \
    wget



RUN apt-get update && apt-get install -y wget build-essential cmake pkg-config libjpeg-dev libtiff5-dev libavcodec-dev libavformat-dev libswscale-dev libv4l-dev libxvidcore-dev libx264-dev libgtk2.0-dev libgtk-3-dev libatlas-base-dev gfortran
RUN curl -fL http://docs.luxonis.com/_static/install_dependencies.sh | bash
# RUN wget http://docs.luxonis.com/_static/install_dependencies.sh && chmod +x install_dependencies.sh && ./install_dependencies.sh

# RUN git clone https://github.com/zeromq/cppzmq.git && cd cppzmq && \
#     mkdir build && \
#     cd build && \
#     cmake .. && \
#     make install

# RUN git clone https://github.com/xtensor-stack/xtl.git && cd xtl && \
#     mkdir build && \
#     cd build && \
#     cmake .. && \
#     make install


# RUN git clone https://github.com/jupyter-xeus/xeus.git && cd xeus && \
#     cmake -D BUILD_EXAMPLES=ON -D CMAKE_BUILD_TYPE=Release . && \
#     make && \
#     make install

# RUN git clone https://github.com/jupyter-xeus/xeus-cling.git && \
#     cd xeus-cling && \
#     mkdir build && \
#     cd build && \
#     cmake .. && \
#     make install

RUN pip3 install depthai==2.5.0
RUN echo 'SUBSYSTEM=="usb", ATTRS{idVendor}=="03e7", MODE="0666"' | tee /etc/udev/rules.d/80-movidius.rules

COPY solution /code/catkin_ws/src/solution
WORKDIR /code/catkin_ws

# COPY assets/vnc/image/root/Desktop/. /root/Desktop/
# COPY assets/vnc/image/root/Documents/. /root/Documents/

# COPY assets/vnc/image/root/icons/. /root/.icons/
# COPY assets/vnc/image/usr/bin/. /usr/bin/
# COPY assets/vnc/image/opt/ros/noetic/share/rviz/. /opt/ros/noetic/share/rviz/


CMD ["dt-launcher-jupyter"]
